app = "my-uas-spk"

[build]
  # If you want Fly to build from your Dockerfile, no image setting is required.

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443
