services:
  - type: web
    name: uas-spk
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    healthCheckPath: /
